### ISSUE TITLE
Remove  XRIT module and add initial Flat support instead

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#103]
## Background
XR Interaction Toolkit module (Assets/Gothic-UnZENity-XRIT) was planned to be a VR setup for developers/new joiners who don't own a Hurricane VR license but want to support the project technically. This module got setup 3 months ago but never maintained. An alternative solution to boot the game without HVR setup is needed. At best, when it will be properly used in the future.

## Solution
Let's create a Flat module which integrates basic support for Gothic in normal game mode without VR. It can be used by developers without HVR/VR and they'll still be able to support the game (e.g. importing Daedalus features). Ok top of it: Flat support is a milestone in the future. Setting the foundation now is a Win-Win for the project and its supporters.

# TODOs
- [ ] XRIT
    - [ ] Remove XRIT module and it's references (Adapter integration and Controls setting)
    - [ ] in this way, alter names of modules in general: Gothic-UnZENity-* to UnZENity-* (shorter names)
- [ ] HVR
    - [ ] Rename our classes from HVR* to VR* and also folder. Justification: HVR itself used this prefix. With a VR* one, we can easily distinguish between HVR and our implementation.
- [ ] Flat
    - [ ] Create module
    - [ ] Add Controls configuration (GameConfiguration.controls setting) for Flat
    - [ ] Ensure the game will use the flat camera and won't render on an HMD. (Some Unity setting like VR.enabled)
    - [ ] Add support for Main menu clicking 
    - [ ] Add basic player controller for WASD+Space+C
    - [ ] (Bonus) Add support for dialog starting and clicking UI box
