### ISSUE TITLE
Foundation: Create automated Play Tests with Unity Test Framework (UTF)

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#105]
Unity offers two types of Tests:
* [Test] - normal NUnit test
* [UnityTest] - Coroutine based tests which can yield waits etc.
@see: https://unity.com/how-to/automated-tests-unity-test-framework

As our game grows, we should think of some basic tests. This ticket will create a framework module and reusable methods (e.g. MovePlayer()) to test it's feasibility.

## TODOs
- [x] create module UnZENity-Tests
- [x] As UTF tests rely on .asmdef modules, we need to add all of our modules to an .asmdef module as well (Otherwise lookups of e.g. Context. won't be possible)
    - [x] Remove Unity.XR dependency from UnZENity.Core.asmdef module
- [x] create common used methods like
    - [x] AlterGameConfiguration()
    - [x] WaitForScene
    - [x] PressButton(Key, seconds)
    - [x] AssertValue()
- [ ] I think of the following initial tests (Skipping a few tests. Can be done later as the foundation is working.)
    - [ ] does the game compile without HVR installed? (e.g. move folder out of Assets folder and test compilation)
    - [ ] does the game boot main menu?
    - [x] does the game boot player in front of Diego?
    - [ ] is music playing?
    - [x] are basic player movements working? (i.e. is HVR controls enabled properly? Even with DeviceSimulator)
