### ISSUE TITLE
Import cutscenes at runtime

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#11]
We need to find a way to import Gothic cutscenes (e.g. opening scene whenever we start a new game).

They are in the files .BIN/.CSL

## TODOs

- [x] Check actual file format of video files
- [x] Find a solution within unity to parse them at runtime
- [x] create an element inside Lab.scene to play a video in a 2D player in front of you. (As a showcase)
- [x] Add documentation for gamers about _how_ they can make videos usable for UnZENity

Boundary:
* This ticket is not about adding cutscenes into the game itself. (e.g. playing the file when we start a new game) --> https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/issues/12

**Comment by lmichaelis** [comment]
Cutscene videos are [Bink Video](https://www.radgametools.com/bnkmain.htm) files. We'd either have to pay them money to license the software (it does appear to have Unity integration), or we could try to leverage [FFmpeg](https://ffmpeg.org/general.html#Video-Codecs) which does have a decoder. Try actually ripped the decoder out of FFmpeg and [embedded it in OpenGothic](https://github.com/Try/OpenGothic/tree/master/game/bink). The other options would be to pre-convert all of the videos to MP4, that's certainly the easiest way of doing it.

**Comment by JaXt0r** [comment]
Hm. I think G1 has 5 cutscenes and G2 about 10. Quite an overkill if we create a parser like ZenKit or the DMusic implementation. But the most flexible one. 😘

Alternatively we could provide an .exe converter where gamers can convert their videos before they play our game and we load the encoded ones at runtime.

**Comment by JaXt0r** [comment]
Investigations:
* Unity has no way of dynamically parsing video data as a stream. It can work with baked VideoClips or with file:// | https:// URLs at runtime only. --> No use to create a dynamic parser like we did with the DMusic synthesizer.
* ffmpeg can easily convert .bik files into .mp4 files: `ffmpeg -i file.bik file.mp4`
* Once converted to .mp4, Unity can read these files at runtime within VideoPlayer

Unsuccessful tests:
* We could add ffmpeg.exe into our build and have a menu button _convert now_.
    * But this is only possible via Assets/StreamingAssets/* (as this is the only folder which will be stored directly on build.)
    * But with this folder we have no option to exclude ffmpeg.exe file from an Android build (no Inspector import filter possible)
    * The ffmpeg tool is per binary ~80MB in size
    * I couldn't get the ffmpeg (arm64 static) build to run within a Unity C# call. It always threw a Win32 exception which is weird.

In G1, we have 5 videos only. We should think of letting the gamer convert their files if they want to see the videos.

Solution:
* Let's add a documentation about "how" the .bik files can be converted to .mp4 files via ffmpeg.
* Let's also add a PS1 script to provide a quick way to convert all files at once
* Within Unity we will then check if the .mp4 file exists only. If so, play it

**Comment by JaXt0r** [comment]
PS1 script for now:

```ps1
try
{
	$processOptions = @{
		FilePath = "./ffmpeg.exe"
		WorkingDirectory = "."
		NoNewWindow = $true
		Wait = $true
	}

	$bikFiles = Get-ChildItem -Path "./" -Filter "*.bik"
	foreach($bikFile in $bikFiles)
	{
		Write-Output "Running conversion for: $bikFile"
		$baseName = $bikFile.Basename		
		Start-Process @processOptions -ArgumentList @("-i", $bikFile, "$baseName.mp4", "-y")
	}
}
catch
{
	  write-warning $_
}
Read-Host -Prompt "Please check if there's any error or if you see all the *.mp4 files. If correct, just copy&paste these video files into your game directory..."
```

**Comment by JaXt0r** [comment]
https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/wiki/Player's-Guide#convert-video-files
