### ISSUE TITLE
Play cutscenes at runtime

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#12]
Follow up of https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/issues/11

## TODOs

- [ ] Find/Implement the right ZenKit.External function which tells the game: Play cutscenes now
- [ ] Integrate video player when new game starts
    - [ ] Idea: Create a scene (similar like loading scene), where you can't walk, but only see the 2D screen in front of you. The rest is black
    - [ ] pause the game's main loop (time ticks, animations, ...) of main game while cutscenes is played
    - [ ] Teleport player back to where it was before the cutscene
- [ ] Logo
  - [x] Skip logo scene if ini file tells so: `playLogoVideos=0`
  - [ ] Respect _Escape_ (Flat/Mock) or _MenuButton_ (VR) to skip logo scene

## Improvements:
- [x] Check on sizes of G1 and G2 videos. Do we need to have different RenderTextures or ar the format (4:3 etc.) at least the same? --> 95% of videos are: 640x360 --> 16:9. To ensure other formats are shown correctly, let's use VideoPlayer.AspectRatio=FitInside (e.g. for logo1 in G1).
- [x] There is an issue with the color usage. Please fix.
![image](https://github.com/user-attachments/assets/5845f89c-61fb-4370-a82a-abcbd39013b0) --> Fixed in [documentation](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/wiki/Player's-Guide#convert-video-files). We need to provide more colorspace information during bik->mp4 conversion

## Boundary:
* Create a new ticket for menu items: _Credits_ and _Play intro_ (which will be delivered later)

## Referenced PRs:
* #118 - Wiki documentation, video player in lab scene, and logo scene on startup (if converted only)

**Comment by lmichaelis** [comment]
The game tells the engine to run a cutscene through the `PlayVideo` and `PlayVideoEx` externals. It looks like `PlayVideoEx` is not used.

**Comment by JaXt0r** [comment]
Assessment of video sizes for G1+G2 movies.
Elements with >x</>!< are differently converted to .mp4 than the default (640x360 - 16:9).
Conversion: ffmpeg -i FILE.bik FILE.mp4 (default values)

Gothic1:
* credits		- 640x360
* extro			- 640x360
* greatPrayer	- 640x360
* intro			- 640x360
* x - logo1			- 400x320	! --> 5:4
* oreheap		- 640x360
* x - playerout		- 640x240	! --> 8:3


Gothic2:
* Addon_Title			- 640x360
* Credits				- 640x360
* Credits2				- 640x360
* Credits_Extro			- 640x360
* DragonAttack			- 640x360
* Extro_AllesWirdGut	- 640x360
* Extro_DJG				- 640x360
* Extro_KDF				- 640x360
* Extro_PAL				- 640x360
* Extro_Raven			- 640x360
* Extro_Xardas			- 640x360
* FishFood				- 640x360
* g2_classic_credits	- 640x360
* intro					- 640x360
* Intro_Addon			- 640x360
* x - Logo1					- 640x480 ! --> 4:3
* Logo2					- 640x360
* LoveScene				- 640x360
* OrcAttack				- 640x360
* OreHeap				- 640x360
* Portal_Raven			- 640x360
* Ship					- 640x360
