### ISSUE TITLE
Re-enable Bench/Barrel/Seat/Throne interaction

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#120]
# Description
We already implemented hero seating functionality in XRIT. Let's re-enable it for HVR. Its implementation will be very similar to NPC dialog clicks and Focus feature (brighten up).

# Tasks
- [ ] Check previous implementation
    - [ ] The components were added via VobCreator.cs via Add component().
    - [ ] Interaction was previously done via colliders/x-ray grabber. Should be at Seat.cs.
- [ ] Reimplement interaction in HVR
    - [ ] add components via prefabs instead of AddCompinent() (like ocNPC.prefab/ocItem.prefab)
    - [ ] Add HVRGrabbable to meshes (like VR/ocItem.prefab has it)
    - [ ] Add HVRFocus to meshes (@see VR/ocItem.prefab)
    - [ ] Once clicked (grabbed), the closest ZS_* (ZenGinSlot) should be selected as interaction point
    - [ ] Player should then be teleported to that spot and direction
    - [ ] Hit a button on left controller (A/B, which is still unused) to "go back" and spawn back to where you were before.
- [ ] Add documentation about the "back" button on Player wiki page

**Comment by JaXt0r** [comment]
Most importantly: The barrel inside OC needs to be used as hiding spot again. 🤣

**Comment by JaXt0r** [comment]
Reimplemented a few months ago.
