### ISSUE TITLE
Hold and Swing 1hand and 2hand weapons based on skill level (1-3)

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#125]
## Description
Gothic has three levels of proficiency/skills for the following melee weapon types:
1. One-handed
2. Two-handed

Levels are:
1. unskilled
2. trained
3. master

We should aim to reimplement the fighting behaviour in VR similar to what the hero is doing in G1 classic.
This includes:
* One-handed weapons need to be hold two-handed when _unskilled_
* Add weight of a weapon if the hero is _unskilled_ or _trained_ to let the sword move with a _weighted_ delay
* Let the hero have some cooldown after a certain amount of combos (like when _unskilled_, the combo is ~3 hits before restarting it). The cooldown can be either "weight of sword is raised during cooldown" and/or we have some visual cooldown like some greyed out vision or pulsating vein 💢 

## Tasks
- [ ] Implement dynamic weight of a melee weapon in hand, based on skill level
  - [ ] Check if the weight will add the movement delay we expected
  - [ ] Apply weight once item is grabbed
  - [ ] Remove weight once item is released (Otherwise it will smash to the ground as it's way too heavy)
  - [ ] For unskilled 1hand and 2hand skills, implement the system, that weight is lowered once two hands grab the item
- [ ] Cooldown
  - [ ] Implement a timer which counts _swings_ during a period of time
  - [ ] Based on skill level more swings can be done one after another
  - [ ] If the counter is down to zero
    - [ ] Add a visual effect of the cooldown (either grey out whole view or add some _fog_ or an icon on screen etc.)
    - [ ] During cooldown, sword swings are nearly impossible (and later: make no damage)
    - [ ] Cooldown needs to be removed after another timer

## Out-of-scope
* This ticket handles weight and cooldown feature only
* It can be tested without any fight process (Can be tested in lab etc.)

## Links
* One-handed weapon skill progression: https://www.youtube.com/watch?v=IZ5sEwCzrR8
* Two-handed weapon skill progression: https://www.youtube.com/watch?v=IqilJzoapT8
