### ISSUE TITLE
Inventory (Backpack): Have selection buttons of Inventory pages (key items, melee, misc, ...)

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#127]
> Hint: Implementation followed a 2D category paginator approach like G1 has.
> Reason: Uncanny vally of having "buttons" and 2D UI menus in parallel was bad.

## Description
Gothic leverages a categorized inventory. In the normal game you need to switch through all categories until you (e.g.) reach key items. Let's add some shortcut buttons in our backpack to switch easily between the categories.

## Tasks
- [x] Add buttons for categories on top of backpack
  - [x] Check on some free assets for category items or leverage some Unicode Emojis
- [x] When tapped via finger, they will be selected
  - [x] Meshes of items will change to new category ones
- [x] Disable remote grabber (red laserpointer) as we should make the category buttons clickable directly only
- [x] Highlight selected category button and
- [ ] Add a label which tells us the currently active category (e.g., on top of pager)

## Bugs
 - [x] Either rotate items in slots or have them aligned top-bottom always. (Based on longest axis)
 - [x] Socketing and unsocketing sound should be removed
 - [x] Grab backpack and put it back should have inventory sound from G1

## Inspirations

Category view in Gothic 1:
![Image](https://github.com/user-attachments/assets/d4024d81-0a87-4cc7-91fb-850a29c96fb3)

Category elements in Gothic Unreal edition:
![Image](https://github.com/user-attachments/assets/f7648dc2-d0b5-4e34-8163-c8b8844e1b95)

Walking Dead: S&S - There's an _Auto_ button on top of backpack. At that spot, I'd say we add our category buttons instead:
![Image](https://github.com/user-attachments/assets/802ef5db-bc66-4006-9bfc-b3a13817c399)
