### ISSUE TITLE
Audio memory consumes about 800MB - optimize caching

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#128]
## Description
When we disable VOBs (culling), we should clean the Audio Memory as it consumes a lot of memory.

## Tasks
- [ ] We need to think about a solution which isn't affecting a lot of CPU cycles (e.g. if we clean Clip when _look around_ culling is kicking in)
- [ ] We need to check if we cache all the audioclip data already and maybe remove some based on TTL
- [ ] Based on performance impact of AudioClip loading/creation, we can offload the logic to a Worker Thread

**Comment by ThomasMountainborn** [comment]
I spoke too soon, the bloated audio usage was due to duplicating the audio clips for every instance where it's used. Reusing the clips drops the memory use in G2 to 53MB.
