### ISSUE TITLE
Lock picking v2

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#132]
> Successor of #32 
> Can be started after: https://github.com/GothicKit/ZenKitCS/pull/12

## Description
Improve haptical feeling and rotation issues

## Tasks
- [x] Resolve rotation issues (Currently the turnaround between 0...360 isn't handled properly. Therefore rotation of hand can be left, but registered as right)
- [x] Add controller vibration for these events: Success, Failure, Breaking, Unlocking (define 4-values of strength and lenght of vibrations)
- [x] Resolve FIXMEs in both classes (e.g. alter data fetching of string:Combination from hard coded to real value)
- [x] LockPicks need to get their own Prefabs applied inside VobCreator.cs (currently LabLockHandler has an example how to apply this prefab)

## Technical details
* Implementation is done within the following two classes:
    * VRDoorLockInteraction.cs
    * VRLockPickInteraction.cs
* Overview of implementation is documented in here: https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/wiki/Hurricane-VR#workflow-for-lock-picking
