### ISSUE TITLE
Eat items (Omnomnom) - v1

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#143]
# Description
We can't consume items in VR as of today. But it would be great to empty Gomez kitchen and eat all his  🧀 🍖 🍄 🥄

# Out of scope
v1 is only an ambient feature where the mesh disappears with eating sound when consumed. No inventory management in player properties or other things need to be done.

# Tasks
- [ ] Add collider in front of VR players mouth
- [ ] Add collision detection component when VOB item enters
- [ ] Load eating sound (might be in a specific animation) and play it on the Players AudioSource component (fetched from NPC properties.Audio)
  - [ ] Hint: there are different sounds based on item type like drinking, munching, ... (fetch type from ItemProperties)
- [ ] Fetch sound length before playing and remove GameObject from scene when done.

**Comment by JaXt0r** [comment]
Implemented and in main.
