### ISSUE TITLE
APK signature - configure shared KeyStore for pipeline and main devs

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#164]
## Background
When building the game from different machines we get different signatures of our built .APK file. With changed signatures, we can't update existing installations but need to fully remove and reinstall the APK. This includes re-uploading game files from Gothic itself.

## Tasks
- [x] Create one key store for pipeline
- [x] Configure it being used by pipeline runs from secret variables on GitHub
- [x] Design: Is it possible to configure and share this key store with our main developers? Any security pitfalls?

**Comment by JaXt0r** [comment]
Solved: https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/pull/353
