### ISSUE TITLE
Lazy load VOB meshes and GO structures on demand only + move calculations to PreCachingScene

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#182]
## Tasks

- [x] Lazy loading
  - [x] Create Loader Component which gets triggered by culling manager for Vobs
  - [x] Add feature flag to disable lazy loading (for developer purposes)
- [x] Cache data (at least bounds are needed for lazy loading and culling groups)
  - [x] CacheFile: _**Bounds**_ of Vobs with meshes will be calculated and stored inside Cache within PreCaching scene
  - [x] CacheFile: TextureArray informaton of all VOBs (texture name to load later when game boots
- [x] World cache
  - [x] World is created during cache scene and lights are placed on top (or simply calculated on top)
  - [x] World chunk information (Index of world element inside .zen file and the corresponding TextureArray information) is stored
  - [ ] Use FrameSkipper during PreCache creation to reduce stutter (+disable FrameSkipper via SpeedUpLoading Dev flag again)
- [ ] Bug Fixes
  - [x] texture array for animated meshes isn't added right now. Please check on original logic and do so.
  - [x] Light information need to be set as parameter into Shader (see _StationaryLight.InitStationaryLights()_)
  - [x] Handling OnEnable and OnDisable for StationaryLight.cs not yet handled. (aka amp below orry isn't becoming on/off and no orange light color is emitted)
  - [x] Light count isn't matching (~300 in original logic, ~1000 in new logic) - Only using LightStatic=false elements as in previous main branch.
  - [x] Check if world chunks have same size/amount as with previous logic when loaded during world loading.
  - [x] Test bounds of BspTreeNodes. I have a feeling they need to be divided by 100 (cm -> m). Simply test with all chunks separated by node and draw Gizmos based on BspTreeNode.Bbox)
  - [x] Further improve performance of loading World Chunks (without stutter: 20sec (each Polygon in a Chunk is skipping frames if needed). --> Check for Jobs.ForEach, Parallel.Foreach, Task.Run, non-await and other options to parallelize the thousands of calls for polygons which assembles into hundreds of chunks. --> Jobs are complex to use, as we need to fetch a lot of data from ZenKit in-and-out of the Job class. / It takes 10 seconds to load world mesh now, due to improved TextureArray cache lookup. Good enough for now.
  - [x] Lazy loading seems to ignore VRPlayer.TeleportTo()
  - [x] LazyLoad of lights need to store the indices (Lights have an index for the Shaders as they store it and use pos+radius when activated). We need to provide dynamic data to the LazyLoad.component and add it to the light once activated. --> Done by calculating position of light and compare it with index in the cached light dictionary.
    - [ ] We need to test it further if working when walking through the world.
  - [x] VobCullingManager.Lights --> The radius need to be set as size. Otherwise standing next to a light and turning away will make it flicker and disable.
  - [x] Objects inside OC aren't added to the list of items. Maybe as they are sub items of something different and therefore not added to cullingmanager? Check with Spacer.
  - [ ] Performance: When spawned inside OC and turning around, the game freezes as a lot of elements need to be created at once.
    - [ ] Either put them in a pool to initialize with each frame
    - [ ] Or pre-cache meshes at world loading time and use them now
    - [ ] or simply put them in a queue and use Frame skipper to do the unit step-by-step based on device performance and framerate
 

## Description
When creating whole world + vobs + NPCs, loading takes up to two minutes. Main part is taken by creating all the GO hierarchy and meshes of NPCs/Monsters as well as briefly activating their routine until they get deactivated. Goal is now to speed up loading and load elements when needed only.

The idea is to have CullingGroup boundaries for:
1. Close distance - Disable/Enable meshes like before
2. Medium distance - GO hierarchy and meshes are created if not yet done first time
3. Far distance - Unneccesary GO hierarchies and meshes get deleted to save memory
![image](https://github.com/user-attachments/assets/22505bfe-1485-4ee9-ad98-ff50857b2565)

Logic could look like this:
1. VobCreator + NpcCreator create an empty GO only.
2. It contains the VobProperties and a component which handles activate/deactivate changes and triggers VobManager/NpcManager to create the whole GO hierarchy once needed (==not yet loaded + enter nearby area)
3. We need to measure the loading time improvement
4. We also need to check if there are spikes in CPU/GPU usage when GO hierarchy + Mesh creation kicks in (which could cause micro stutters - but let's test it first) - Best spot to check: Entering Old Camp (Many VOBs and many NPCs)

## Ticket expansion
As the Boundaries of Vobs need to be calculated and stored on Culling groups, I want to precalculate it on PreCachingScene. Working on this, we can also move more tasks from world loading (every time) to pre catching (once). Details are described in the tasks above.

## Out-of-scope
* Particle and Decal sizes aren't calculated for the bounds of Vobs so far
* Sub-particle sizes (e.g. for burning torches) aren't either

**Comment by JaXt0r** [comment]
Update: Solved.
Added missing _RenderQueue.Transparent_ information to water Shader did the trick

---

Water has some issues after re-adding animations (movement of textures and change of textures). Depending on view angle and distance:

![image](https://github.com/user-attachments/assets/ec08c403-4aa9-4f52-89b6-263c7a0a236f)

**Comment by JaXt0r** [comment]
VobCreator - reparenting issue: Chickensticks in the sky
![image](https://github.com/user-attachments/assets/aaf4b7dd-b305-4819-be9a-25e9a3ba40c9)

![image](https://github.com/user-attachments/assets/95e63690-6c82-4083-9234-aa8ed43b0247)

**Comment by JaXt0r** [comment]
In Gomez' room, the culling is broken. We don't see the chair and objects on it.

![Image](https://github.com/user-attachments/assets/c4e1fc17-4ea6-44bb-ac1f-a3244fe361ec)

**Comment by JaXt0r** [comment]
Update: Solved. Vfs.OverwriteBehaviour.Older prioritizes patches.vdf files now.

---

Texture for image frame on Gomez' wall has the v1 texture again. We need texture v2 or so.

![Image](https://github.com/user-attachments/assets/f49ecd62-3432-4f4c-9208-8d7c4bbc8c06)
