### ISSUE TITLE
HVR: Chest opening

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#19]
Chests contain a separate mesh for their lid. We can leverage this to create open and close animation properly.

## TODOs
- [x] Update prefab of ocMobContainer and add a sub-element "BIP01 CHEST_.*_0"."BIP01 CHEST_.*_1" (Prefab GOs are replaced via regex with loaded ZenKit data).
- [x] Add the neccessary HVR components to the prefab GO -> Added with https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/issues/57
- [x] Adjust parameters to enable only partial opening of the lid. (I assume the same value can be applied for all chests as they're very similar) -> Added with https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/issues/57
- [x] The chests are by default physics based. We need to find a way to ignore walls as it might be the chest lid will stuck inside world (e.g. lid will collide with a wall when opened)
- [x]  (Bonus): Animation of chest opening has a sound. Check in animation data which rotation % it will play and add it as event to the chest.
- [x] (Bonus): Let the lid close automatically when we move away from it. (G1 itself will never leave chests open.)

![Image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/ff3b7877-e029-4f26-bfc5-c9e00078290d)

**Comment by JaXt0r** [comment]
Only open topic: The lid should stay open when we're very close. Otherwise we always need to grab with one hand while looting.

**Comment by JaXt0r** [comment]
Solved via: #81
