### ISSUE TITLE
HVR: Put loot into chests - Fixed slots

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#22]
As a first iteration, we can leverage HVRs slot loot grid. We will fill it with the data from the chest's inventory.

## TODOs

- [x] Implement HVR's slot canvas for chests
- [x] Add event: Whenever lid is opened (5% etc.), then spawn items into slot (Items are already stored inside VobProperties.component on the chest prefab)
- [x] Add event: Whenever lid is closed, then de-spawn items which are in slots

![Image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/f89fb03e-4c0d-4f6a-9667-432e5aef466d)

A notable mention is Medieval Dynastie and it's loot slot system (it slightly rotated with the chest opening).
