### ISSUE TITLE
HVR: Door opening - Update physics

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#23]
Doors can't be opened as of now. Let's change this.

## TODOs
- [x] Doors are ocMobInteractable, separate them in VobCreator via name, so that they will get their own prefab -> Added with #57 
- [x] Inside prefab, implement the sub-GOs via regex-wildcards and add the HVR components -> Added with #57 
- [x] The doors are by default physics based. We need to find a way to ignore walls as it might be the door will stuck inside world (e.g. door knob will collide with wall)
- [x] (Bonus): Animation of door opening has a sound. Check in animation data which rotation % it will play and add it as event to the door.

![Image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/0ae1679a-9a09-4450-806b-7c144d01f593)

**Comment by JaXt0r** [comment]
Partially done via: #81

Just sound is missing.
