### ISSUE TITLE
Load menu from Daedalus C_Menu

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#24]
The main menu is currently created manually. As Gothic has a presets for its menu, we can leverage this (at least partially...).

## TODOs

- [ ] Load C_Menu and its data from Daedalus VM
- [ ] Leverage its width/height values to create a canvas menu inside Unity dynamically
- [ ] Remove elements which aren't useful for us (e.g. graphic settings which we don't want)
- [ ] Add additional elements which make sense for VR

**Comment by lmichaelis** [comment]
I'm claiming this! After I've done my reorganizing, I'd like to go with this since it has the potential of teaching me more about Unity :)
