### ISSUE TITLE
HVR: Fix main menu usage

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#25]
Currently (afaik?) the main menu isn't usable with HVR's VR player. For XRIT we added custom logic to it. Let's do the same in here.

## TODOs

- [x] Check on XRIT's VRPlayer (_Assets/Gothic-UnZENity-XRIT/Resources/Prefabs/VRPlayer/VRPlayer-MainMenu.prefab_) on how the menu was added to it
- [x] Try to reimplement for HVR Player
- [x] (Bonus) Check if you can come up with a modular logic, which just sub-prefabs the same MainMenu logic, so that we don't need to build the menues twice (for each player - XRIT + HVR)

**Comment by JaXt0r** [comment]
The implementation was quite easy. Main menu buttons are already recognized by HVR. We just need to disable gravity and walking from HVR player. Pointing and clicking on menu items already worked out-of-the-box.
