### ISSUE TITLE
HVR: Create HVRDeviceSimulator

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#26]
HVR doesn't support XRITs XR Device Simulator. There might be multiple options. Let's explore our best option.

## TODOs

- [ ] Check on alternative packages on top of HVR. e.g. https://www.youtube.com/watch?v=-LRJt0cD4xk
- [ ] Implement it
- [ ] Do not forget to add it to the XRDeviceSimulator feature flag (based on active Context 😜)
- [ ] Check that it will not interfer when a developer is leveraging XRIT. (e.g. we need to hide it behind a compiler flag or add it to the manifest.json with a UnityEditor menu item)

**Comment by JaXt0r** [comment]
Implementation detail: I created another GitHub repository which we include via Package Manager. Therefore XRIT users or HVR users never need to download anything from scratch. Gothic-UnZENity is taking care already. More details can be found here: https://github.com/Gothic-UnZENity-Project/hvr-simulator
