### ISSUE TITLE
Implement G1 savegame loading - Items + Hero position

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#28]
Our game only supports _New Game_ at the moment. We want to support official G1 savegames. As ZenKit supports save&reload, let's leverage it to have G1 compatible save games for Gothic-UnZENity.

Links:
* [SaveGame.cs](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/SaveGame.cs) at ZenKit
* [TestSaveGame.cs](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit.Test/TestSaveGame.cs) at ZenKit.Tests

## TODOs

- [x] Create a Gothic save slot where you changed some stuff. (e.g. moved item, killed NPC)
- [x] Implement test to load this save game
- [x] Check if the loaded assets match expectations and if the world is correctly loaded
- [x] Implement Loading menu inside main menu (according to G1 look&feel)
