### ISSUE TITLE
HVR: Fix in game menu usage

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#29]
Currently (afaik?) the in game menu isn't usable with HVR's VR player. For XRIT we added custom logic to it. Let's do the same in here.

## TODOs

- [ ] Check on XRIT's VRPlayer (_Assets/Gothic-UnZENity-XRIT/Resources/Prefabs/VRPlayer/VRPlayer.prefab_) on how the menu was added to it
- [ ] Try to reimplement for HVR Player
- [ ] Bind a button on Controller to open the menu
- [ ] (Bonus) Check if you can come up with a modular logic, which just sub-prefabs the same Menu logic, so that we don't need to build the menues twice (for each player - XRIT + HVR)
