### ISSUE TITLE
Savegame saving - v1

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#30]
> I recommend picking this up after: #28 

Our game only supports _New Game_ at the moment. We want to support official G1 savegames. As ZenKit supports save&reload, let's leverage it to have G1 compatible save games for Gothic-UnZENity.

Links:
* [SaveGame.cs](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/SaveGame.cs) at ZenKit

## TODOs

- [x] Create a Gothic save slot where you changed some stuff. (e.g. moved item, killed NPC)
- [x] Implement test to save a current state during gameplay into a save game
- [x] Check If the saved assets match expectations when loaded
    - [x] into G1 classic
    - [x] into Gothic-UnZENity
- [x] Implement Save button inside game menu

## Test tasks
- [x] Create a Component to compare two save games. It should loop through the VOBs (etc.) and compare order of elements and also value of Vob.Properties.
- [x] Test it via: Create an original G1 Save game, load it into UnZENity, save it to another SaveGame slot, and compare values.

## Hints:
* I figured out, that G1 save games store NPCs inside Vobs[].Type=oCNPC.
* It also stores NPCs/Monsters only! if they are nearby hero during save time.
* Also if we load a G1 save game, walk away from an NPC and save again, the updated save game won't include the far away NPC
