### ISSUE TITLE
Implement trade system

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#31]
G1 features a quite complex trade system where you can put single elements or bunch of 10s into a middle slot. Then you need to compensate the amount with the amount from your wares. We need to implement the system in an authentic, but VR modern way.

![Image](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/assets/120568393/441dc392-644c-4beb-af53-710431447ffe)

## Pre-conditions
* Talking to NPCs needs to be implemented

## TODOs
- [ ] a 2D menu should be opening like in G1
- [ ] The inventory items from trader and hero needs to be spawned (mesh created) and put into the visible slots
- [ ] grabbing items via hands to move them from edges to the center
- [ ] close the trade when costs match or were higher only

## Hints
* The 2D menu is the afaik easiest way to implement the UI. Feel free to suggest an immersive VR alternative.
* This is a very vague ticket with a lot of open topics to decide. Let's be creative. 🥳
