### ISSUE TITLE
Lock picking - v1

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#32]
G1 provides us with data for Left-Right combination of locks. Let's stay close to the original and implement a logic, where we lock pick via hand rotation as well.

## TODOs
- [x] Add collider (etc.) on the lock
- [x] read the value of LR combination from VobProperties attached to the object
- [x] Add sounds for "breaking" and "passing" a try
- [x] Save value of "chest opened" inside VobProperies once done
