### ISSUE TITLE
DialogTrigger: point towards NPC to start discussion

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#34]
As of now, NPCs have a collider which checks if you walk into them and start the dialog.

It should be changed to work via Ray caster.

# TODOs
- [x] Add "point to" Ray caster information
- [x] highlight the NPC brighter, when pointed at (like in original G1)
- [x] Start dialog on button click
