### ISSUE TITLE
Dialog: Update UI

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#35]
> Hint: Implementing this task can highly benefit #31

As of now the UI of dialogs is - rudimentary. 🤣
We need to adjust, fix and improve it.

## TODOs
- [x] Fix order of elements inside dialog box (afaik they sometimes switch order when e.g. talking to Bloodwyn)
- [x] Alter the UI of dialogs to align with original G1 look (2D dialog box is fine for now)
- [x] Add hover event and highlight an entry, if selected via Ray caster. (@see MainMenu-LoadMenu for a reference of Event component which fetches hover events in VR-UIs)

**Comment by lmichaelis** [comment]
Also:
- [ ] Make the player unable to move when in dialog
- [x] Move the dialog window into the player's view immediately (or indicate that they're in a dialog and attach the window to the NPC)
