### ISSUE TITLE
Inventory - recognize batches of items

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#59]
In G1 you can drop x amount of an item onto the surface (e.g. 13 ore) and it will only show one mesh. We need to recognize the stack size of a mesh when put into inventory (merge with existing) and put out of inventory.

**TODOs**:
- [ ] Store amount of items
    - [x] retrieve it from ZenKit when Vob is loaded (Open point. Will be solved via https://github.com/GothicKit/ZenKitCS/issues/7)
    - [ ] as Component on the mesh object
- [ ] (bonus) When Item is put into inventory, it should merge with the existing items (e.g. 2 in inventory + 3 put into inventory = 5 items but only one inventory slot used)
- [x] When item is hovered, show batch size (amount) on label (fixed with #298)

When items are in VR hand
* we have another menu on top, where we can "rip off" 1, 10, 100 items.
* and a fourth element is for "stacking" the item in the other hand to "re-stack" e.g., mutliple ore together
(Maybe for another ticket?)
