### ISSUE TITLE
VOB Culling: Optimize loading performance and ignore Frustum Culling/Occlusion Culling

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#76]
**about Loading performance:**  
When we load VOBs, they're all visible and rendered during loading time. This is slowing down render performance during loading.
When the loading is done, CullingGroup logic is immediately kicking in and fine.

**about Frustum Culling / Occlusion Culling**  
Items and rocks are culled out, when we (e.g.) turn around and they're in our back. But NPCs will still work and interact with objects or walk among them. If we cull them out, but NPCs are still there, we will cause some logical (where's the mushroom, if not rendered?) and rendering issues (NPCs will fall through holes in the world).

## TODOs
- [ ] Culling during loading
    - [ ] Plainly disable all meshes once created during loading time
    - [ ] When the Culling kicks in (after player is spawned), CullingGroup will handle re-activation automatically
    - [ ] If Culling is disabled via GameConfiguration, just SetActive() all of them directly. @see NpcMeshCullingManager.cs
- [ ] Ignore Frustum Culling  Occlusion Culling
    - [ ] For NPCs/VobSounds, we found a workaround, if we set the Sphere to the size of the BoundingBox area. For CullingGroups it means, there's no Frustum/Occlusion, as we are _in_ the object. Let's leverage it like this.
- [ ] Bonus: WorldMesh Frustum/Occlusion
    - [ ] We also need to check how Worl tiles will be handled as we can't disable them when turning around for the same reasons as the rock topic above. Either fix it with this or create a new ticket, please.
