### ISSUE TITLE
Item collision v1 - Items in our hand should never collide

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#88]
> Hint: follow-up ticket: #70 

## Background
Classical G1 isn't optimized for VR. (Thanks, Captain Obvious... 🤣). We therefore have the following issues:
* When we grab items with our hands (either remote or direct), they might stuck in walls etc. As G1 doesn't have physics and collision checks for moving items. (In fact carrying an item isn't possible in the original game. Except some item throwing feature and melee/bow carrying.).
* Gamers also might get distracted from being stopped by walking with a sword through a door if they don't align the mesh in hands perfectly.

In a first step (to overcome the stuck issues), we should therefore disable item collisions when they're in our hands. Notable games leveraging it as well are _Garden of the Sea_ and _Into the Radius_ (at least the backpack has no collision with items).

## TODOs
- [x] Disable collisions for items while being grabbed and carried until we release them from our hands.
- [x] Check if Unity's Layers are feasible as they can have a collision matrix. E.g. moving item meshes to another layer (change flag value) so that they don't collide with the rest of the world.
- [x] Ensure the collision is immediately brought back once we release the item. As it would fall through the world otherwise.

**Comment by JaXt0r** [comment]
Fixed within: #81(Commit: https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/commit/c1278a5532d296f617e63dcae03f198b10abeeeb)

Leveraged a new Layer+CollisionMatrix change to handle this feature properly.
