### ISSUE TITLE
Dialog subtitles

### ISSUE THREAD

**Issue by JaXt0r** [Gothic-Unity-Project/Gothic-Unity#96]
## TODOs
- [x] Subtitles for NPCs should be visible above their head and are rotated towards us (As we can't move in the future it will be a fixed value when dialog starts)
- [x] Subtitles for our hero
    - [x] should be slightly below our view (golden cut or so)
    - [x] They should have a delay when moving with us for convenience (you can reuse the Chapter switch screen logic - there's a movement delay implemented already) - [HVRIntroduceChapter.cs](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/blob/main/Assets/Gothic-UnZENity-HVR/Scripts/Components/HVRIntroduceChapter.cs)
- [x] Dialog settings can be altered on our MainMenu
- [x] (Bonus) We can also read and write the subtitle setting from gothic.ini. The ini file is already read in our game. We just need to implement the save as well. - Please read+save the settings inside PlayerPrefsManager then

**Comment by BoroBongo** [comment]
This [PR](https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/pull/166) Started V1 of Subtitles:
- Player locked in place during cutscene. 
- Subtitles displayed for both NPC and Player (With the name of the 'talker' above message).

**Comment by JaXt0r** [comment]
Everything's implemented from this Ticket.
